#logging.level.root=trace
## Postgresql DB1 - "fdm_db"
#spring.datasource.url=jdbc:postgresql://localhost:5432/cx
#spring.datasource.username=postgres
#spring.datasource.password=1234
spring.datasource.url=jdbc:postgresql://yd-fdmtestdb01.nix.vimpelcom.ru:5432/fdm_db
spring.datasource.username=fdm_user
spring.datasource.password=12fdmuser)(
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true

integration.document-server-url= https://document-service-func-eafdmmart.apps.yd-m6-kt22.vimpelcom.ru
integration.auth-server-url= http://localhost:8080